mds: fix build failure with ronDB disabled
When building without RonDB enabled, the build was failing with the
following error:

  /home/bertschinger/git/pnfs-lattice/src/mds/main.c:1899:41: error: ‘rondb_boot_epoch’ undeclared (first use in this function)
   1899 |                                         rondb_boot_epoch, 65536U,
        |                                         ^~~~~~~~~~~~~~~~

The parameter `rondb_boot_epoch` is passed to `remove_manifest_init()`
regardless of the state of `HAVE_RONDB`, even though `rondb_boot_epoch`
is only defined when `HAVE_RONDB` is defined.

To resolve this, either `rondb_boot_epoch` can be always defined, or
`remove_manifest_init()` should only be called when building with RonDB.

The remove_manifest code appears to be intended to be used regardless of
storage backend, so the latter solution can be ruled out. Instead, the
definition of `rondb_boot_epoch` is moved outside of the
`ifdef HAVE_RONDB` block.

The parameter is also renamed to `boot_epoch` since it isn't really
RonDB specific anymore.

Fixes: 8fe650807232 ("mds: async REMOVE (delete-at-ack) + deferred parent_touch (default off)")